# Collection level default variables
# not supported by Ansible, so workaround is to created a dedicated
# role and make other roles depend on it

# discard any modified files in the git repositories
deploy_force_clone: true
