- name: Clone repo
  git:
    repo: "{{ libxdc_url }}"
    dest: "{{ libxdc_root }}"
    version: "{{ libxdc_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: "{{ force_clone }}"
  tags:
    - clone
