- name: Clone repo
  git:
    repo: "{{ targets_url }}"
    dest: "{{ targets_dest }}"
    version: "{{ targets_revision | default(omit) }}"
    depth: "{{ git_clone_depth | default(omit) }}"
    force: "{{ force_clone }}"
  tags:
    - clone
