- name: Ensure minimal deps are available
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - git
    - build-essential

- name: Clone repo
  git:
    repo: "{{ capstone_url }}"
    dest: "{{ capstone_root }}"
    version: "{{ capstone_revision | default('master') }}"
    depth: "{{ git_clone_depth | default(omit) }}"
